/*
Sources :
    https://www.reddit.com/r/namenerds/comments/a2geoi/whats_the_weirdest_punniest_play_on_words_type_of/
    https://www.confetti.co.uk/inspire-and-advice/relationships/joke-names-phonetic-puns-prank-names/
*/

const names = [
    'Al Coholic',
    'Al E.Gater',
    'Amanda Huggenkiss',
    'Amanda Lynn',
    'Amanda Lynne (a mandoline)',
    'Amy Stake (A mistake)',
    'Anita Bath',
    'Anita Man',
    'Anita Room',
    'Arty Fischel',
    'Barb Dwyer (Barbed wire)',
    'Barry D.Hatchett',
    'Bea O’Problem',
    'Ben Dover',
    'Bennie Factor',
    'Carole Singer',
    'Chester Minit',
    'Chris P Baker (Crispy baker)',
    'Chuck Up',
    'Clare Voyant',
    'Crystal Ball',
    'Dick Tate',
    'Dinah Mite',
    'Don Keigh',
    'Doris Shutt',
    'Doug Graves (Dug graves)',
    'Drew A. Head',
    'Earl E.Bird',
    'Eileen Dover',
    'Ella Vader (Elevator)',
    'Emma Nate',
    'Emma Roids (Haemorrhoids)',
    'Eura Snotball',
    'Felix Cited',
    'Frank N.Stein',
    'Gerry Atrick',
    'Gilda Lily',
    'Gladys Canby',
    'Hedda Hare',
    'Helen Hywater',
    'Herbie Hind',
    'Heywood U Cuddleme',
    'Holly Wood',
    'Homer Sexual',
    'Horace Cope',
    'Hugh Jass (Huge ass)',
    'Hugh Raye',
    'I. P. Freely',
    'Ima Hogg',
    'Iona Mink',
    'Ivana Tinkle',
    'Jack Hoff (Jack off)',
    'Jack Pott',
    'Jacqueline Hyde (Jekyll and Hyde)',
    'Jacques Strap',
    'Jay Walker',
    'Jed I. Knight (Jedi Knight)',
    'Jim Nasium',
    'Joe King',
    'Justin Case',
    'Justin Thyme',
    'Kay Oss',
    'Kirsten Swore',
    'Laura Lynn Hardy (Laurel and Hardy)',
    'Lee King (Leaking)',
    'Lee Vitoff',
    'Levy Tate',
    'Libby Doe',
    'Lois Price',
    'Lori Driver',
    'Lorne Mowers',
    'Lynn C.Doyle',
    'Manuel Labour',
    'Marius Quick',
    'Mary Christmas',
    'Max E.Mumm',
    'May B.Dunn',
    'Maya Buttreeks',
    'Mel N.Colley',
    'Mike Hawk (My cock)',
    'Mike Rotch (My crotch)',
    'Miles A.Head',
    'Mona Lott',
    'Oliver Clothesoff',
    'Ollie Tabooger',
    'Ophelia Pane (I feel your pain)',
    'Paige Turner (Page turner)',
    'Paul Bearer (Pallbearer)',
    'Phil Landers',
    'Phil McCann',
    'Phil McCracken (Fill my crack in)',
    'Philipa Bucket (Fill up a bucket)',
    'Polly C.Holder',
    'Poppy Cox',
    'Reg Oyce',
    'Rex Cars',
    'Rhoda Camel',
    'Rhoda Wolff (Rode a wolf)',
    'Rick O’Shea',
    'Robyn Banks (Robbing banks)',
    'Russ Tinayle',
    'Ruth Less',
    'Sally Forth',
    'Sandy Beech',
    'Serge A.Head',
    'Seymour Stuff (see more stuff)',
    'Shirley U.Care',
    'Stan Dupp',
    'Sue Age',
    'Sue Flay (Souffle)',
    'Sum Ting Wong (Something wrong)',
    'Teresa Brown (Trees are brown)',
    'Teresa Crowd (Three\'s a crowd)',
    'Teresa Green (Trees are green)',
    'Tim Burr (Timber)',
    'Titus Zell',
    'Toby Lerone (Toblerone)',
    'Ty Prayer (Typewriter)',
    'Upton O.Goode',
    'Wade Moore',
    'Warren Peace',
    'Wayne Kerr (Wanker)',
    'Yul B.Allwright',
    'Zoltan Pepper (Salt and pepper)',
  ]